# description: Deploys to Development when a push occurs to any branch that is not the default branch
name: Deploy Development
on:
  push:
    branches-ignore:  
      - $default-branch

jobs:
  ms-deploy:
    uses: gmi-actions/msdeploy/.github/workflows/msdeploy-workflow.yml@v1
    with:
      platform: ExamplePlatform                       # CHANGE ME TO YOUR DESIRED DEPLOYMENT PLATFORM!!!
      environment: Development
      deployment_name: example.generalmills.com       # CHANGE ME TO THE NAME OF THE SITE OR SERVICE BEING DEPLOYED!!!
      source: example.generalmills.com.zip            # CHANGE ME TO THE LOCATION OF THE ARTIFACT BEING DEPLOYED!!!
      destination: wwwroot$\example.generalmills.com  # CHANGE ME TO THE LOCATION OF THE SITE OR SERVICE BEING DEPLOYED!!!
      repository_name: web-packages-snapshot-local    # Typically will use web-packages-snapshot-local for Development
      # stop_and_start_app_pool: true                 # UNCOMMENT IF THE APP POOL SHOULD BE STOPPED BEFORE DEPLOYMENT AND STARTED AFTER DEPLOYMENT
      # stop_and_start_service: true                  # UNCOMMENT IF THE SERICE SHOULD BE STOPPED BEFORE DEPLOYMENT AND STARTED AFTER DEPLOYMENT
      # additional_arguments: -enableRule:doNotDelete # UNCOMMENT IF YOU NEED TO PASS ADDITONAL ARGUMENTS TO THE MSDeploy COMMAND
    secrets: inherit